services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${STGR_DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${STGR_DATABASE_USER}
      - POSTGRES_PASSWORD=${STGR_DATABASE_PASSWORD}
      - POSTGRES_DB=${STGR_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - ${STGR_PGADMIN_PORT}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${STGR_PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${STGR_PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
